const COUNTRIES = [
  { pt: "Afeganistão", en: "Afghanistan" },
  { pt: "África do Sul", en: "South Africa" },
  { pt: "Albânia", en: "Albania" },
  { pt: "Alemanha", en: "Germany" },
  { pt: "Andorra", en: "Andorra" },
  { pt: "Angola", en: "Angola" },
  { pt: "Antígua e Barbuda", en: "Antigua and Barbuda" },
  { pt: "Arábia Saudita", en: "Saudi Arabia" },
  { pt: "Argélia", en: "Algeria" },
  { pt: "Argentina", en: "Argentina" },
  { pt: "Armênia", en: "Armenia" },
  { pt: "Austrália", en: "Australia" },
  { pt: "Áustria", en: "Austria" },
  { pt: "Azerbaijão", en: "Azerbaijan" },
  { pt: "Bahamas", en: "Bahamas" },
  { pt: "Bahrein", en: "Bahrain" },
  { pt: "Bangladesh", en: "Bangladesh" },
  { pt: "Barbados", en: "Barbados" },
  { pt: "Bélgica", en: "Belgium" },
  { pt: "Belize", en: "Belize" },
  { pt: "Benim", en: "Benin" },
  { pt: "Bielorrússia", en: "Belarus" },
  { pt: "Bolívia", en: "Bolivia" },
  { pt: "Bósnia e Herzegovina", en: "Bosnia and Herzegovina" },
  { pt: "Botsuana", en: "Botswana" },
  { pt: "Brasil", en: "Brazil" },
  { pt: "Brunei", en: "Brunei" },
  { pt: "Bulgária", en: "Bulgaria" },
  { pt: "Burkina Faso", en: "Burkina Faso" },
  { pt: "Burundi", en: "Burundi" },
  { pt: "Butão", en: "Bhutan" },
  { pt: "Cabo Verde", en: "Cape Verde" },
  { pt: "Camarões", en: "Cameroon" },
  { pt: "Camboja", en: "Cambodia" },
  { pt: "Canadá", en: "Canada" },
  { pt: "Catar", en: "Qatar" },
  { pt: "Cazaquistão", en: "Kazakhstan" },
  { pt: "Chade", en: "Chad" },
  { pt: "Chile", en: "Chile" },
  { pt: "China", en: "China" },
  { pt: "Chipre", en: "Cyprus" },
  { pt: "Colômbia", en: "Colombia" },
  { pt: "Comores", en: "Comoros" },
  { pt: "Congo", en: "Republic of the Congo" },
  { pt: "Congo, República Democrática do", en: "Democratic Republic of the Congo" },
  { pt: "Coreia do Norte", en: "North Korea" },
  { pt: "Coreia do Sul", en: "South Korea" },
  { pt: "Costa do Marfim", en: "Ivory Coast" },
  { pt: "Costa Rica", en: "Costa Rica" },
  { pt: "Croácia", en: "Croatia" },
  { pt: "Cuba", en: "Cuba" },
  { pt: "Dinamarca", en: "Denmark" },
  { pt: "Djibuti", en: "Djibouti" },
  { pt: "Dominica", en: "Dominica" },
  { pt: "Egito", en: "Egypt" },
  { pt: "El Salvador", en: "El Salvador" },
  { pt: "Emirados Árabes Unidos", en: "United Arab Emirates" },
  { pt: "Equador", en: "Ecuador" },
  { pt: "Eritreia", en: "Eritrea" },
  { pt: "Eslováquia", en: "Slovakia" },
  { pt: "Eslovênia", en: "Slovenia" },
  { pt: "Espanha", en: "Spain" },
  { pt: "Estados Unidos", en: "United States" },
  { pt: "Estônia", en: "Estonia" },
  { pt: "Eswatini", en: "Eswatini" },
  { pt: "Etiópia", en: "Ethiopia" },
  { pt: "Fiji", en: "Fiji" },
  { pt: "Filipinas", en: "Philippines" },
  { pt: "Finlândia", en: "Finland" },
  { pt: "França", en: "France" },
  { pt: "Gabão", en: "Gabon" },
  { pt: "Gâmbia", en: "Gambia" },
  { pt: "Gana", en: "Ghana" },
  { pt: "Geórgia", en: "Georgia" },
  { pt: "Granada", en: "Grenada" },
  { pt: "Grécia", en: "Greece" },
  { pt: "Guatemala", en: "Guatemala" },
  { pt: "Guiana", en: "Guyana" },
  { pt: "Guiné", en: "Guinea" },
  { pt: "Guiné Equatorial", en: "Equatorial Guinea" },
  { pt: "Guiné-Bissau", en: "Guinea-Bissau" },
  { pt: "Haiti", en: "Haiti" },
  { pt: "Honduras", en: "Honduras" },
  { pt: "Hungria", en: "Hungary" },
  { pt: "Iêmen", en: "Yemen" },
  { pt: "Ilhas Marshall", en: "Marshall Islands" },
  { pt: "Ilhas Salomão", en: "Solomon Islands" },
  { pt: "Índia", en: "India" },
  { pt: "Indonésia", en: "Indonesia" },
  { pt: "Irã", en: "Iran" },
  { pt: "Iraque", en: "Iraq" },
  { pt: "Irlanda", en: "Ireland" },
  { pt: "Islândia", en: "Iceland" },
  { pt: "Israel", en: "Israel" },
  { pt: "Itália", en: "Italy" },
  { pt: "Jamaica", en: "Jamaica" },
  { pt: "Japão", en: "Japan" },
  { pt: "Jordânia", en: "Jordan" },
  { pt: "Kiribati", en: "Kiribati" },
  { pt: "Kuwait", en: "Kuwait" },
  { pt: "Laos", en: "Laos" },
  { pt: "Lesoto", en: "Lesotho" },
  { pt: "Letônia", en: "Latvia" },
  { pt: "Líbano", en: "Lebanon" },
  { pt: "Libéria", en: "Liberia" },
  { pt: "Líbia", en: "Libya" },
  { pt: "Liechtenstein", en: "Liechtenstein" },
  { pt: "Lituânia", en: "Lithuania" },
  { pt: "Luxemburgo", en: "Luxembourg" },
  { pt: "Macedônia do Norte", en: "North Macedonia" },
  { pt: "Madagáscar", en: "Madagascar" },
  { pt: "Malásia", en: "Malaysia" },
  { pt: "Malaui", en: "Malawi" },
  { pt: "Maldivas", en: "Maldives" },
  { pt: "Mali", en: "Mali" },
  { pt: "Malta", en: "Malta" },
  { pt: "Marrocos", en: "Morocco" },
  { pt: "Maurício", en: "Mauritius" },
  { pt: "Mauritânia", en: "Mauritania" },
  { pt: "México", en: "Mexico" },
  { pt: "Mianmar", en: "Myanmar" },
  { pt: "Micronésia", en: "Micronesia" },
  { pt: "Moçambique", en: "Mozambique" },
  { pt: "Moldávia", en: "Moldova" },
  { pt: "Mônaco", en: "Monaco" },
  { pt: "Mongólia", en: "Mongolia" },
  { pt: "Montenegro", en: "Montenegro" },
  { pt: "Namíbia", en: "Namibia" },
  { pt: "Nauru", en: "Nauru" },
  { pt: "Nepal", en: "Nepal" },
  { pt: "Nicarágua", en: "Nicaragua" },
  { pt: "Níger", en: "Niger" },
  { pt: "Nigéria", en: "Nigeria" },
  { pt: "Noruega", en: "Norway" },
  { pt: "Nova Zelândia", en: "New Zealand" },
  { pt: "Omã", en: "Oman" },
  { pt: "Países Baixos", en: "Netherlands" },
  { pt: "Palau", en: "Palau" },
  { pt: "Panamá", en: "Panama" },
  { pt: "Papua Nova Guiné", en: "Papua New Guinea" },
  { pt: "Paquistão", en: "Pakistan" },
  { pt: "Paraguai", en: "Paraguay" },
  { pt: "Peru", en: "Peru" },
  { pt: "Polônia", en: "Poland" },
  { pt: "Portugal", en: "Portugal" },
  { pt: "Quênia", en: "Kenya" },
  { pt: "Quirguistão", en: "Kyrgyzstan" },
  { pt: "Reino Unido", en: "United Kingdom" },
  { pt: "República Centro-Africana", en: "Central African Republic" },
  { pt: "República Dominicana", en: "Dominican Republic" },
  { pt: "República Tcheca", en: "Czech Republic" },
  { pt: "Romênia", en: "Romania" },
  { pt: "Ruanda", en: "Rwanda" },
  { pt: "Rússia", en: "Russia" },
  { pt: "Samoa", en: "Samoa" },
  { pt: "San Marino", en: "San Marino" },
  { pt: "Santa Lúcia", en: "Saint Lucia" },
  { pt: "São Cristóvão e Nevis", en: "Saint Kitts and Nevis" },
  { pt: "São Tomé e Príncipe", en: "São Tomé and Príncipe" },
  { pt: "São Vicente e Granadinas", en: "Saint Vincent and the Grenadines" },
  { pt: "Seicheles", en: "Seychelles" },
  { pt: "Senegal", en: "Senegal" },
  { pt: "Serra Leoa", en: "Sierra Leone" },
  { pt: "Sérvia", en: "Serbia" },
  { pt: "Singapura", en: "Singapore" },
  { pt: "Síria", en: "Syria" },
  { pt: "Somália", en: "Somalia" },
  { pt: "Sri Lanka", en: "Sri Lanka" },
  { pt: "Sudão", en: "Sudan" },
  { pt: "Sudão do Sul", en: "South Sudan" },
  { pt: "Suécia", en: "Sweden" },
  { pt: "Suíça", en: "Switzerland" },
  { pt: "Suriname", en: "Suriname" },
  { pt: "Tailândia", en: "Thailand" },
  { pt: "Taiwan*", en: "Taiwan" },
  { pt: "Tajiquistão", en: "Tajikistan" },
  { pt: "Tanzânia", en: "Tanzania" },
  { pt: "Tchéquia", en: "Czechia" },
  { pt: "Timor-Leste", en: "East Timor" },
  { pt: "Togo", en: "Togo" },
  { pt: "Tonga", en: "Tonga" },
  { pt: "Trinidad e Tobago", en: "Trinidad and Tobago" },
  { pt: "Tunísia", en: "Tunisia" },
  { pt: "Turcomenistão", en: "Turkmenistan" },
  { pt: "Turquia", en: "Turkey" },
  { pt: "Tuvalu", en: "Tuvalu" },
  { pt: "Ucrânia", en: "Ukraine" },
  { pt: "Uganda", en: "Uganda" },
  { pt: "Uruguai", en: "Uruguay" },
  { pt: "Uzbequistão", en: "Uzbekistan" },
  { pt: "Vanuatu", en: "Vanuatu" },
  { pt: "Vaticano", en: "Vatican City" },
  { pt: "Venezuela", en: "Venezuela" },
  { pt: "Vietnã", en: "Vietnam" },
  { pt: "Zâmbia", en: "Zambia" },
  { pt: "Zimbábue", en: "Zimbabwe" }
];

export default COUNTRIES;
